### ISSUE TITLE
footer overflows page's content

### ISSUE THREAD

**Issue by daniel-acuna** [daniel-acuna/reviewer_assignment#17]
fix the footer so it doesn't overflow the content. Check this bug by making window short.

**Comment by daniel-acuna** [comment]
it looks awesome! thanks

On Feb 11, 2015, at 7:24 AM, Tupleblog <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #17https://github.com/daniel-acuna/reviewer_assignment/issues/17 via a2479f0https://github.com/daniel-acuna/reviewer_assignment/commit/a2479f0a6724741a4b37eb2dbd21aabd61fb54ec.

**Comment by tupleblog** [comment]
You're welcome. However, it still needs a little tweak, I will do tomorrow :-)

**Comment by titipata** [comment]
I think we should divide the footer into two columns. Right now it takes a bit of space.
