### ISSUE TITLE
Problem installing ortools on Mac OS X

### ISSUE THREAD

**Issue by daniel-acuna** [daniel-acuna/reviewer_assignment#20]
This may grant a change of the linear programming library? (again!). See http://stackoverflow.com/questions/26593497/cant-install-or-tools-on-mac-10-10 for a reference

**Comment by titipata** [comment]
I put an issue on Google or-tools [discussion forum](https://groups.google.com/forum/#!forum/or-tools-discuss), hope there are someone solve the problem.

**Comment by titipata** [comment]
quick fix for those who do not have `or-tools` and want to contribute in the website, comment line 19 i.e.

``` python
import paper_reviewer_matcher as prm
```

in [`review_assign/views.py`](https://github.com/daniel-acuna/reviewer_assignment/blob/master/reviewer_assignment_website/review_assign/views.py)

**Comment by daniel-acuna** [comment]
@titipata i did a quick fix that bypasses the import in system with no or-tools installed (see 0c2b462)

**Comment by titipata** [comment]
So, we don't need to comment out the line anymore. Thanks Daniel.

**Comment by daniel-acuna** [comment]
Yeah, the direct link to your posted question to or-tools is https://groups.google.com/forum/#!topic/or-tools-discuss/_Zns5sEIv2w

**Comment by daniel-acuna** [comment]
A quick fix is to install ortools with easy_install by directly using the egg provided by pypi. For example, the last version of ortools in egg form is available at https://pypi.python.org/packages/2.7/o/ortools/ortools-1.3750-py2.7-macosx-10.9-intel.egg#md5=3a653c90a1d5ef70769df4346bb28a94

The following command does the trick in our system:
`
pip install ortools
`

and then

`
sudo easy_install https://pypi.python.org/packages/2.7/o/ortools/ortools-1.3750-py2.7-macosx-10.9-intel.egg#md5=3a653c90a1d5ef70769df4346bb28a94
`

Even though this complains because it does not find other dependent packages, it still works.
