### ISSUE TITLE
Create documentation for reviewer assignment part of the system

### ISSUE THREAD

**Issue by daniel-acuna** [daniel-acuna/reviewer_assignment#22]
It should contain a general explanation of the process and the idea behind the assignment method. Also, it should be an added view to the review_assign app

**Comment by titipata** [comment]
@daniel-acuna I already created the skeleton documentation. Can you add plain documentation to the page?

**Comment by daniel-acuna** [comment]
Closed by acbfe1c23ed6ac4400d442e039375343f449c37f
