### ISSUE TITLE
Create documentation for home

### ISSUE THREAD

**Issue by daniel-acuna** [daniel-acuna/reviewer_assignment#24]
Simple documentation explaining the two parts of the system

**Comment by titipata** [comment]
Already add the skeleton html and link to home documentation.

**Comment by daniel-acuna** [comment]
should we close this then?

**Comment by titipata** [comment]
Not for now, I think we can close after we write most of the documents and provide links to reviewer documentation

**Comment by daniel-acuna** [comment]
Closed by acbfe1c23ed6ac4400d442e039375343f449c37f
