### ISSUE TITLE
Add Facebook, Twitter, and Google+ buttons

### ISSUE THREAD

**Issue by daniel-acuna** [daniel-acuna/reviewer_assignment#33]
See http://klab.smpp.northwestern.edu/h-index.html for an example

**Comment by titipata** [comment]
It will be Kording lab's Twitter but how about Google+ and Facebook?

**Comment by daniel-acuna** [comment]
Hmm i doesnt need to be associated with an account. We will just be adding a button to tweet from the page easily, and the "likes" button from Google+ and FB.

**Comment by daniel-acuna** [comment]
it would be button to share on google+ and facebook i guess
